//
//  MyGroupsModel.swift
//  IdEatThere
//
//  Created by Brilyante Apps LLC on 1/9/23.
//

import Foundation
import Combine
import SwiftUI
import Firebase
import FirebaseAuth
import FirebaseFirestoreSwift
import FirebaseStorage


class MyGroupsModel : ObservableObject {
    
    
    
    @Published var hasGroups : Bool = true

    @Published var groupsAttending = [Groups]()
    @Published var groupsHosting = [Groups]()
    @Published var groupsHostDetails = [User]()
    @Published var groupsRestaurantsList = [RestaurantsList]()
    
    @Published var allGroupsIn = [Groups]()
    
    // Setting up initial group details
    @Published var groupName = ""
    @Published var datePicked = Date()
    @Published var groupPhoto : UIImage?
    @Published var allowInvitesToGroup = false
    
    private var groupId = ""
    
//    private let groupsDataService = GroupsDataService()
//    private var cancellables = Set<AnyCancellable>()
    
    let db = Firestore.firestore()
    
    
//    init() {
//
//        addSubscribers()
//    }
    
    // MARK: - Ensure login, get userId
    func checkLogin() -> Bool {
        let loggedin = Auth.auth().currentUser == nil ? false : true
 //       self.userInfo()
        
        return loggedin
    }
    
    func getLoggedInUserId() -> String {
        let userId = Auth.auth().currentUser?.uid ?? ""
        
        return userId
        
    }
    
    
    // MARK: - Queries
    func queryGroupsAttending() {
        
        DispatchQueue.init(label: "getUserGroupsAttending").async {
            
            
            UserManagerModel().userGroupsAttending() {groupsAttending in
                
                // Update the UI in the main thread
                
                DispatchQueue.main.async {
                    self.groupsAttending = groupsAttending
                    self.hasGroups = true
//                    print(self.hasGroups)
//                    print(self.groupsAttending)

                }
            }
        }
    }
    
    func queryGroupsHosting() {
        
        DispatchQueue.init(label: "getUserGroupsHosting").async {
            
            
            UserManagerModel().userGroupsHosting() {groupsHosting in
                
                // Update the UI in the main thread
                DispatchQueue.main.async {
                    self.groupsHosting = groupsHosting
//                    print(self.groupsHosting)
                }
                
            }
        }
        
    }
    
    func queryRestaurantsInGroups(groupsId : String) {
        // Creates a query from the names of restaurants in firebase to yelp and outputs all the info into the user groups
        
        // Ensure user is logged in
        guard self.checkLogin() != false else {
            
            // Use is not logged in
            return
        }
        
        
        DispatchQueue.init(label: "getRestaurantList").async {
            
            
            self.list(groupsId: groupsId ?? "") { groupsRestaurantList in
                self.groupsRestaurantsList = groupsRestaurantList
            }
        }
        
        
        
    }
    
    func list(groupsId: String, completion: @escaping ([RestaurantsList]) -> Void) {
        
        let restuarantQuery = db.collection("groups").document(groupsId).collection("restaurantsList")
        
        restuarantQuery.getDocuments { snapshot, error in
            
            if snapshot != nil && error == nil {
                
                var restaurants = [RestaurantsList]()
                
                // Loop through returned restaurant docs
                for doc in snapshot!.documents {
                    
                   let restaurant = try? doc.data(as: RestaurantsList.self)
                    
                    if let restaurant = restaurant {
                        
                        restaurants.append(restaurant)
                    }
                }
                
                completion(restaurants)
                
            }
            
        }
    }
    
    // MARK: - Create Group Form
    
    func createGroup(groupName: String, groupPhoto: UIImage?, datePicked: Date, allowInvites: Bool, completion: @escaping (Error?) -> Void) {
        
        // Ensure user is logged in
        guard self.checkLogin() != false else {
            
            // Use is not logged in
            return
        }
        
        
        // Get userId
        let userId = self.getLoggedInUserId()
        
        // Set document id
        let userDocumentId = userId
        
        // Create subcollection (if not already existing) for active groups
        let subCollectionPath = db.collection("users").document(userDocumentId).collection("activeGroups")
        
        // Create path to subcollection with autoGeneratedId document
        let autoIdDocumentPath = subCollectionPath.document()
        
        // Set the new GroupId as the autoGeneratedID document
        let groupId = autoIdDocumentPath.documentID
        
        // Make sure to the new documentid (same as groupid) in the subcollection with a timestamp field
        let activeGroupsDocPath = subCollectionPath.document(groupId)
        
        activeGroupsDocPath.setData(["time": FirebaseFirestore.FieldValue.serverTimestamp()])
        
        // Create the new group path collection with user's filled out fields from the create groups form
        
        let groupPath = db.collection("groups").document(groupId)
        
        // TODO: Add uploading image option (convert to url string) (reference userManager)
        groupPath.setData(["groupName" : groupName,
                           "attendees" : FieldValue.arrayUnion([""]),
                           "host" : FieldValue.arrayUnion(["\(userId)"]),
                           "date" : Timestamp(date: datePicked),
                           "allowInvites" : allowInvites]) { (error) in
            
            if let error = error {
                
                
                completion(error)
            }
            
            else {
                completion(error)
            }
            
            
        }
        
        
        
    }
    
    func resetGroupDetailForm() {
        self.groupName = ""
        self.datePicked = Date()
        self.allowInvitesToGroup = false
        
    }
    
    // MARK: - Add Restaurants to Group
    func addRestaurantNameToMyGroup(groupId: String, restaurantName : String, restaurantId : String, restaurantAlias: String, completion: @escaping (Error?) -> Void) {
        // Restaurant Name is stored in firebase
        
        // Ensure user is logged in
        guard self.checkLogin() != false else {
            
            // Use is not logged in
            return
        }
        
        // Get reference to the database
        let restaurantListPath = db.collection("groups").document(groupId).collection("resturantsList")
        
        
        // Create document id for adding restaurant
        
        DispatchQueue.init(label: "userAddedRestaurantToGroup").async {
            
            UserManagerModel().userAddedRestauranttoGroup(groupId: groupId, restaurantName: restaurantName) { error in
                
                
                

                
                
            }
        }
    }
    func addSubscribers() {
        
        
//        groupsDataService.$groupsArray
//            .sink { [weak self] (returnedgroupsArray) in
//                self?.groupsArray = returnedgroupsArray
//            }
//            .store(in: &cancellables)
 
    }
    
}
